### ISSUE TITLE
Function `load_checkpoint` doesn't load to CPU

### ISSUE THREAD

**Issue by swtyree** [dlichy/ShapeAndMaterial#3]
The end of [`save_load_checkpoint.py:13`](https://github.com/dlichy/ShapeAndMaterial/blob/3a278a4fe402e536a39fe3353e6f79ffa0598420/models/save_load_checkpoint.py#L13) is commented out, so even if the `--gpu` flag is omitted, the model still tries to load to the GPU. (Probably because the tensors are saved as coda tensors?)

**Comment by dlichy** [comment]
Thanks for reporting this. It should be working now. Let me know if there are any other issues.
